# Generated by Django 3.1.1 on 2020-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
